### PR TITLE
updated to work with keycloak 3.4.3. Removed some unused dependencies

### PR DESCRIPTION
**Pull request by Mihai-B**
I am only using Keycloak since 3.4.3 but I had to edit some of the files in order to make it work. Just sharing back what I did to make it work.

### CODE REVIEW

**Comment by nfriend** [comment]
Thanks for the pull request @Mihai-B!  We will take a look.

**Comment by nfriend** [comment]
Hi @Mihai-B - It looks the main change was adding in `?html` to the `value` property in some of the `.ftl` templates?  Just curious what problem this solved?  (We'd like to test it out in our own Keycloak install.)  It does look like this attribute [has been deprecated](https://freemarker.apache.org/docs/ref_builtins_string.html#ref_builtin_html).

Also - we'd prefer not to remove files from the `third-party-lib` directory since each folder is just the full download of the library.  Would you mind submitting a new PR without these dependency deletions?

**Comment by Mihai-B** [comment]
Hi @nfriend The changes was to **remove** the `?html` from `.ftl` files because apparently this breaks keycloak(at least for version 3.4.3). That's it.

A simple test is just use your current code for the theme and keycloak 3.4.3 and when you want to log in northing will appear, and a error message is logged in the keycloak console.

As for the dependencies, I can submit a new PR without the removal of them, but why would you prefer all those dependencies there ? they only occupy space and are never used.

1 more question not regarding programing: Why do you refer yourself to plural?

**Comment by nfriend** [comment]
Ah, sorry, I was reading the diff backwards.  This makes sense.

The main reason we'd like to leave the dependencies is for simplicity - by not messing with anything in the `third-party-lib` directory we can be sure the dependencies are unaltered and can be upgraded by just dropping in a replacement folder (without needing to comb through and figure out which files are unnecessary).  

The real solution would be to just switch to a package manager like NPM and not check in dependencies here at all.

Regarding my use of "we" - I'm responding on behalf of my whole team at MAXIMUS DeltaWare :)

**Comment by Mihai-B** [comment]
I reverted back the files deleted.

**Comment by nfriend** [comment]
Great, thanks @Mihai-B!

**Pull request merged**
